Metrcis/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
Style/Documentation:
  Enabled: false
StyleAccessModifierDeclarations:
  Exclude:
    - lib/liam/message_processor.rb
