name: Main

on: [pull_request]

jobs:
  vm-job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        version: 3.7

    - name: Install pip
      run: |
        python -m pip install --upgrade pip
        pip install localstack

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby_version: 2.6.3

    - name: Build
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run tests
      run: |
        localstack start
        RAILS_ENV=test bundle exec rspec -fd
